export enum Role {
    ROL_ADMIN = 'ROL_ADMIN',
    ROL_PROFESIONAL = 'ROL_PROFESIONAL',
    ROL_PROPIETARIO = 'ROL_PROPIETARIO',
    ROL_MESA_ENTRADA = 'ROL_MESA_ENTRADA',
    ROL_EMPLEADO_CARGA = 'ROL_EMPLEADO_CARGA',
    ROL_PARCELAMIENTO = 'ROL_PARCELAMIENTO',
    ROL_PRES_POST = 'ROL_PRES_POST',
    ROL_TECNICO = 'ROL_TECNICO',
    ROL_LINDERO = 'ROL_LINDERO'
  }
  
