export enum Role {
    ROL_USER = 'ROL_USER',
    ROL_ADMIN = 'ROL_ADMIN',
    ROL_PROFESIONAL = 'ROL_PROFESIONAL',
    ROL_PROPIETARIO = 'ROL_PROPIETARIO',
    ROL_EMPLEADO = 'ROL_EMPLEADO',
    ROL_EMPLEADOME = 'ROL_EMPLEADOME'
  }
  
