export enum Role {
    ROL_USER = 'ROL_USER',
    ROL_ADMIN = 'ROL_ADMIN',
    ROL_PROFESIONAL = 'ROL_PROFESIONAL',
    ROL_CLIENTE = 'ROL_CLIENTE',
    ROL_EMPLEADO = 'ROL_EMPLEADO',
    ROL_EMPLEADO_ME = 'ROL_EMPLEADO_ME'
  }
  
