
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    endpoint: 'endpoint',
    production: false,
    secret_key: "clave",
    siteKey: "sitekey"
  };
