
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    endpoint: 'http://192.168.0.15:8000',
    production: false,
    secret_key: "clave",
    siteKey: "6LczrNocAAAAAD0vzNtL744UUkNpbZepxB0GRyFw"
  };
